export const authConstants = {
    LOGIN_REQUEST:' LOGIN_REQUEST',
    LOGIN_FAILURE:' LOGIN_FAILURE',
    LOGIN_SUCCESS:' LOGIN_SUCCESS',
    LOGOUT_REQUEST:'  LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'  LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'  LOGOUT_FAILURE',
}
export const userConstants = {
    USER_REGISTER_REQUEST:'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
     USER_REGISTER_FAILURE:'  USER_REGISTER_FAILURE',
}
export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST:'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE:'  GET_ALL_CATEGORY_FAILURE',
    CREATE_CATEGORY_REQUEST:'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS:'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE:'  CREATE_CATEGORY_FAILURE',
}
export const productConstants = {
    GET_ALL_PRODUCT_BYSLUG_REQUEST:'GET_ALL_PRODUCT_BYSLUG_REQUEST',
    GET_ALL_PRODUCT_BYSLUG_SUCCESS:'GET_ALL_PRODUCT_BYSLUG_SUCCESS',
    GET_ALL_PRODUCT_BYSLUG_FAILURE:'  GET_ALL_PRODUCT_BYSLUG_FAILURE',
    GET_ALL_PRODUCT_REQUEST:'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS:'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE:'  GET_ALL_PRODUCT_FAILURE',
    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS:'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE:'  CREATE_PRODUCT_FAILURE',
}
export const initalDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST:'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS:'GET_ALL_INITIAL_DATA_SUCCESS',
     GET_ALL_INITIAL_DATA_FAILURE:'GET_ALL_INITIAL_DATA_FAILURE',
   
}